django_workflow/urls.py
"""django_workflow package urls."""

from django.urls import path

import django_workflow.views as workflow_views


urlpatterns = [
    path("", workflow_views.FlowListView.as_view(), name="flow-list"),
    path("new", workflow_views.FlowCreateView.as_view(), name="flow-create"),
    path("delete/<int:pk>/", workflow_views.FlowDeleteView.as_view(), name="flow-delete"),
    path("<int:pk>/", workflow_views.FlowView.as_view(), name="flow"),
    path(
        "<int:pk>/continue",
        workflow_views.FlowContinueView.as_view(),
        name="flow-continue",
    ),
    path(
        "<int:pk>/diagram",
        workflow_views.FlowDiagramView.as_view(),
        name="flow-diagram",
    ),
]

example_project/example/urls.py
from django.contrib import admin
from django.urls import include, path

from django_workflow_engine import workflow_urls
from example_project.workflow.views import CustomListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('workflow/', workflow_urls(list_view=CustomListView)),
    path('', include('workflow.urls'))
]

example_project/workflow/urls.py
from django.urls import path

from .views import home, select_user


app_name = "workflow"

urlpatterns = [
    path("", home, name="home"),
    path("select-user/", select_user, name="select-user"),
]

example_project/workflow/models.py
from django.db import models

# Create your models here.

example_project/workflow/forms.py
from django import forms
from django.contrib.auth import get_user_model


User = get_user_model()


def get_user_choices():
    yield None, "-----"

    for user in User.objects.all():
        yield user.pk, user.username


class SelectUserForm(forms.Form):
    user = forms.ChoiceField(choices=get_user_choices, required=False)

example_project/workflow/views.py
from django.contrib.auth import get_user_model, login, logout
from django.core.exceptions import ValidationError
from django.shortcuts import redirect, render
from django.urls import reverse

from django_workflow_engine.views import FlowListView
from .forms import SelectUserForm

User = get_user_model()


def home(request):
    context = {
        "title": "Home",
        "select_user_form": SelectUserForm(initial={"user": request.user.pk})
    }

    return render(request, "workflow/home.html", context=context)


def select_user(request):
    form = SelectUserForm(request.POST)

    if not form.is_valid():
        raise ValidationError("Invalid change user form")

    if form.cleaned_data["user"]:
        new_user = User.objects.get(pk=form.cleaned_data["user"])

        login(request, new_user)
    else:
        logout(request)

    return redirect(reverse("flow-list"))


class CustomListView(FlowListView):
    template_name = "workflow/list_flows.html"

example_project/workflow/templates/workflow/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Example Project - Django Workflow Engine</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

example_project/workflow/templates/workflow/home.html
{% extends 'workflow/base.html' %}

{% block content %}
<h1>Example Project - Django Workflow Engine</h1>

<h2>Select user</h2>
<form action="{% url 'workflow:select-user' %}" method="post">
    {% csrf_token %}
    {{ select_user_form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

example_project/workflow/templates/workflow/list_flows.html
<h1>This is a custom (beautiful) HTMl template</h1>

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          crossorigin="anonymous">
</head>

<a href="{% url 'flow-create' %}">Create flow</a>
<div class="container">
    <div class="text-center mt-5">
        <h1>Workflows:</h1>
        <p class="lead">A list of all workflows on the platform</p>
        {% for flow in object_list %}
            <div class="container">
                {% include "includes/requirement_summary.html" with flow=flow %}
                <form action="{% url "flow-delete" flow.pk %}" method="POST">
                    {% csrf_token %}
                    {% if flow.on_manual_step or not flow.is_complete %}
                        <a href="{% url "flow-continue" flow.pk %}">Progress requirement</a>
                    {% else %}
                        <a href="{% url "flow" flow.pk %}">View requirement</a>
                    {% endif %}
                    <button>
                        Delete requirement
                    </button>
                </form>
            </div>
            <hr>
        {% empty %}
            <div class="container">
                <p>
                    No workflows yet.
                </p>
            </div>
        {% endfor %}
    </div>
</div>